DATABASE_USER={{ include "awx-db-user" . }}
DATABASE_NAME={{ include "awx-db-name" . }}
DATABASE_HOST={{ include "awx-db-host" . }}
DATABASE_PORT={{ include "awx-db-port" . }}
DATABASE_PASSWORD={{ include "awx-db-password" . }}
DATABASE_ADMIN_PASSWORD={{ include "awx-db-password" . }}
MEMCACHED_HOST={{ .Release.Name }}-memcached
MEMCACHED_PORT=11211
RABBITMQ_HOST={{ .Release.Name }}-rabbitmq
RABBITMQ_PORT={{ .Values.rabbitmq.service.port }}
AWX_ADMIN_USER={{ .Values.default_admin_user }}
AWX_ADMIN_PASSWORD={{ .Values.default_admin_password }}
