dependencies:
   - name: rabbitmq
     version: 6.17.2
     repository: https://kubernetes-charts.storage.googleapis.com/
     condition: rabbitmq.enabled
   - name: postgresql
     version: 8.3.4
     repository: https://kubernetes-charts.storage.googleapis.com/
     condition: postgresql.enabled
   - name: memcached
     version: 3.2.2
     repository: https://kubernetes-charts.storage.googleapis.com/
     condition: memcached.enabled
